### ISSUE TITLE
Richtext and Markdown cells

### ISSUE THREAD

**Issue by forrestbao** [codepod-io/codepod#111]
@lihebi I know that @li-xin-yi's code  already supports adding Richtext/Markdown cells. Can we add it to the main branch?

**Comment by lihebi** [comment]
The demo @forrestbao was referring to is [this](https://github.com/li-xin-yi/sharing-edited-monaco-flow/blob/main/src/components/QuillNode.js), using Quill editor.

We had used [slate](https://www.slatejs.org/examples) editor in CodePod before.

There's one more editor that looks more feature-rich, the [ProseMirror](https://github.com/yjs/y-prosemirror/). There are two more editors based on ProseMirror:
- https://remirror.io/
- https://milkdown.dev/

I vote for Milkdown, because:
- it supports markdown syntax (all ProseMirror-based editors support this)
- you can move the blocks using the left handle, like Notion.

**Comment by lihebi** [comment]
I don’t think it’s meaningful to switch between code and doc (even though Jupyter has it). We just need to switch between languages.

**Comment by forrestbao** [comment]
@lihebi so what do you suggest? Switching between Python and Markdown?
