### ISSUE TITLE
Warn user when deleting repo/pod/scope

### ISSUE THREAD

**Issue by lihebi** [codepod-io/codepod#350]
Show a warning and let the user confirm when the user deletes:
1. a repo
2. a pod or scope

**Comment by senwang86** [comment]
PR #353

**Comment by lihebi** [comment]
> a undo/redo might be good enough for the pod/scope.

Agreed.

**Comment by senwang86** [comment]
> Undo/redo isn't straightforward because we need to handle react-flow, editor content, scopes, and Yjs all at once.
> 
> Therefore, I added confirmation for the deletion operation for pods and scopes (#407). This should be good enough to prevent accidental clicks, and we don't need to rush the undo/redo feature.

I think the "confirmation pop-up" is a bit overwhelming for deleting a pod or repo, as it asks for more operations for users during coding. The accidental clicks may reveal that the position of the "delete" button is not ideal.

**Comment by lihebi** [comment]
Good point, let's keep an eye on thinking about where to put the "delete" button.

**Comment by forrestbao** [comment]
I'd vote for the confirmation. 

The true cause of accidental deletion is not the location of the delete button but many other factors, e.g., change of mind or inaccurate pointing of the mouse cursor. They can be well solved by adding a confirmation. Both DeepNote and CoLab have undo/redo for deletion and insertion of cells, which are very convenient. In details, DeepNote's undo/redo is for both cell editing and cell insertion/deletion, whereas CoLab's undo/redo is only for cell insertion/deletion and CoLab leaves cell content undo/redo to the editor/browser. 

![image](https://github.com/codepod-io/codepod/assets/438579/c3c8ae96-b340-4c34-ae10-5ce33048fe4b)

Both DeepNote and CoLab put the delete button in the toolbar per cell. I never had accidental deletion due to the location.
